name: Task Manager
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  manage-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - run: pip install requests

      - run: mkdir -p data

      - run: python manager.py
        env:
          GH_GIST_ID: ${{ secrets.GH_GIST_ID }}
          GH_GIST_PAT: ${{ secrets.GH_GIST_PAT }}

      - name: Check if sent.json exists
        run: ls -la data/sent.json || echo "File not found"

      - uses: actions/upload-artifact@v4
        with:
          name: point-log
          path: data/sent.json