name: Task Punisher
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  punish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - run: pip install requests

      - run: mkdir -p data

      - run: python scripts/punish.py
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}

      - name: Check if sent.json exists
        run: ls -la data/sent.json || echo "File not found"

      - uses: actions/upload-artifact@v4
        with:
          name: sent-log
          path: data/sent.json